### ISSUE TITLE
Se rompe al instalar usando pypi

### ISSUE THREAD

**Issue by lukio** [joac/singing-girl#11]
querido! lo quise instalar por pypi y no pude. abrazo!

$ pip install singing_girl
```
Downloading/unpacking singing-girl
  Downloading singing-girl-0.0.3.tar.gz
  Running setup.py egg_info for package singing-girl
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/home/tryton/.virtualenvs/tryton34/build/singing-girl/setup.py", line 8, in <module>
        long_description=open('README.rst').read(),
    IOError: [Errno 2] No such file or directory: 'README.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/home/tryton/.virtualenvs/tryton34/build/singing-girl/setup.py", line 8, in <module>

    long_description=open('README.rst').read(),

IOError: [Errno 2] No such file or directory: 'README.rst'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/tryton/.virtualenvs/tryton34/build/singing-girl
Storing complete log in /home/tryton/.pip/pip.log
```

**Comment by joac** [comment]
Gracias por el reporte! la verdad me colgué bastante en ver los issues
